added data preprocessor for pko-ExMix
paust-team/pko-t5 pull request #2
Opened 2022-11-14 07:24 UTC by HwiyeolJo

2022-11-14 12:10 UTC, 1dennispark requested changes
코드가 너무 테스트하기 힘들어보입니다.

각 data_name 별로 함수로 따로 빼서 unit-test 를 수행하는게 좋지 않을까요?
이렇게 하다간 하나의 task 에서 버그가나면 전체 데이터를 다시 돌려야할 수 있습니다.

그러기 위해선 한 process 마다 [유닛테스트](https://docs.pytest.org/en/7.2.x/)를 해놓는게 좋아보입니다.

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                        'output_ids': tokenizer.encode(input_text, add_special_tokens=False),
저희가 tokenizer 를 fast 버전을 쓰고있는데요. rust의 tokenizers 라이브러리를 통해 최대한 많은 parallelism 을 하기 위해서는 뭉쳐서 한꺼번에 처리하는 것이 좋습니다.

`tokenizer.encode(...)`로 하나씩 하는게 아니라 `tokenizer(<list of string>, add_special_tokens=False).input_ids`를 통해 최대한 멀티쓰레드를 활용하는 쪽으로 하는게 속도면에서 좋을듯합니다.

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                    chat_logs_tok.append(tokenizer.encode(c + '\n', add_special_tokens=False))
T5 에서 줄바꿈 문자는 최대한 안넣는게 좋지 않을까 싶습니다.

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +
해당 에러들이 왜 발생할까요?
print 만 하지 마시고 stacktrace 형태로 남겨주시는게 좋지 않을까요?

`traceback.print_exc`으로 남기는게 어떨까요? https://docs.python.org/3/library/traceback.html#traceback.print_exc
그러면 더 에러가 잘 보일거같습니다.

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                file_object = open(f"{file_name}", "rb")
아무리 read mode 라지만 닫아주셨으면 합니다.

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                    task_family += "cn)"
화살표로 표현하는게 맞을까요? 주석으로 설명 부탁드립니다.

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                file_object = open(f"{file_name}", "rb")
ditto

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                file_object = open(f"{file_name}", "rb")
ditto

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                        input_text = f"질의: {qa['question']}\n제목: {data['doc_title']}\n본문: {data['paragraphs'][0]['context']}"
역시나 문자열은 빼주세요.

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                input_text = f"제목: {datasets['Meta(Acqusition)']['doc_name']}\n본문: {datasets['Meta(Refine)']['passage']}"
ditto

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                file_object = open(f"{file_name}", "rb")
ditto

2022-11-14 12:10 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +    selected_task_family = [ "dialogue" ]
[fire 라이브러리](https://github.com/google/python-fire)를 사용하는게 어때요? 그러면 이런거 파라미터로 받을 수 있어보입니다.

2022-11-14 13:36 UTC, HwiyeolJo commented on pkot5/data_preprocessor.py
> +                    chat_logs_tok.append(tokenizer.encode(c + '\n', add_special_tokens=False))
매 대화의 turn 을 줄 바꿈으로 표현하려 했는데, 다른 아이디어 있으실까요!

2022-11-14 13:36 UTC, HwiyeolJo commented on pkot5/data_preprocessor.py
> +                file_object = open(f"{file_name}", "rb")
네ㅠ

2022-11-14 13:41 UTC, HwiyeolJo commented on pkot5/data_preprocessor.py
> +                    task_family += "cn)"
translation task 중에서 일단 해당 언어에서 다른 언어로 바뀐다는 정보가 필수인 것 같아 일단은 화살표로 표현했는데요,
ExMix 에서는 translation 이 없어서 표준이랄게 없다보니 자유롭게 했습니다.

task_family 라고 적어둔 것에는 가능한 짧게 표현하고,
이후 prompt 를 "translate from korean to japanese" 와 같이 주는 게 어떨까 생각합니다

2022-11-14 13:42 UTC, HwiyeolJo commented on pkot5/data_preprocessor.py
> +                        input_text = f"질의: {qa['question']}\n제목: {data['doc_title']}\n본문: {data['paragraphs'][0]['context']}"
문자열이 "질의:" 같은 것을 말씀하시나요?

2022-11-14 14:35 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                    chat_logs_tok.append(tokenizer.encode(c + '\n', add_special_tokens=False))
원래 T5 논문들은 전부 줄바꿈 대신 space 를 넣습니다. encoder-decoder 구조상 그런식으로 해도 될겁니다 ㅎ

2022-11-14 14:36 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                    task_family += "cn)"
아 저는 prompt 만 적는다고 생각했는데요. task family 로 하고 prompt 를 따로 적는다면 좋은거같습니다 ㅎ

2022-11-14 14:37 UTC, 1dennispark commented on pkot5/data_preprocessor.py
> +                        input_text = f"질의: {qa['question']}\n제목: {data['doc_title']}\n본문: {data['paragraphs'][0]['context']}"
줄바꿈 문자열을 말한거였는데 안들어갔네요 수정했습니다.

2022-12-27 09:00 UTC, 1dennispark requested changes
`.ipynb_checkpoints` 디렉토리는 쓸모 없는거같습니다.

다 좋은데 함수레벨로 좀 쪼개면 좋겠네요. 너무 큰 파일을 유지하는거같아 버전관리 입장에서도 안좋아보여서요.
그래도 코드는 이제 괜찮은거같습니다.

2023-06-21 05:38 UTC, 1dennispark approved these changes

2023-06-21 05:38 UTC, merged